### ISSUE TITLE
Review by Sophia Brothers

### ISSUE THREAD

**Issue by sophiabrothers1** [brucejczhang/covid_data#2]
1. Summary:
This paper focuses on interpreting COVID-19 demographic data to predict populations and communities with a higher likelihood of being at high risk during the pandemic. The paper uses a logistic regression model to evaluate how demographic factors contribute to high-risk probabilities. Key findings indicate that living in rural areas, being male, and being aged 40–50 years significantly correlate with a higher risk of adverse outcomes during the pandemic.
2. Strong positive points:
    1. This is an extremely detailed first draft. The parts that are done are done well so I commend you for that effort
    2. Abstract is everything it needs to be, good job
    3. Also just overall this is a very interesting and relevant topic 
3. Critical improvements needed:
    1. Add estimand to intro
    2. Parquet files not csv files
    3. Add idealized survey to appendix
    4. Fix broken cross references/citations
    5. Use testthat for your scripts
    6. Overall beef up your model section
4. Suggestions for improvement:
    1. Expanding on some parts in the discussion section
    2. Include more external literature
    3. Expand on your captions
    4. Add variable interaction to simulation
5. Evaluation:
    * R/Python cited (1/1 pts)
        * Cited
    * Data cited (1/1 pts)
        * Cited
    * Class paper (1/1 pts)
        * Done
    * LLM documentation (1/1 pts)
        * Done
    * Title [2/2 pts)
        * Informative, I know what you’re saying
    * Author, date, and repo (2/2 pts)
        * Done
    * Abstract (4/4 pts)
        * Great abstract, no comments
    * Introduction (4/4 pts)
        * Well done - this is not a needed comment but perhaps you could make the “what was found” part a little more spelled out. Its definitely there but it took me a second to process that that was what I was reading
    * Estimand (0/1 pts)
        * State the estimand using the word estimand!
    * Data (8/10 pts)
        * Typo in overview section
        * Would love more detail on the data cleaning, like be more specific about what you did
    * Measurement (4/4 pts)
        * Great
    * Model (4/10 pts)
        * Figure cross reference failed
        * Variables could be more well-defined - need justification for why they were included (can use literature to back it up)
        * Add situations where the model may not be appropriate.
        * Mention the software used to implement the model
        * For model justification, you do justify your model and mention linear as an alternative example, but there isnt enough detail on your consideration of other models as a whole
    * Results (8/10 pts)
        * Figure captions could be more detailed
        * Use modelsummary
    * Discussion (8/10 pts)
        * Could use some citations in sec 5.1, would love to see more about the impact these findings have on the population
        * I would mostly emphasize expanding upon the ‘what did we learn about the world’ sections
    * Prose (4/6 pts)
        * Some typos
    * Cross-references (1/1 pts)
        * Theyre done but some are broken just fyi
    * Captions (1/2 pts)
        * Need to be sufficiently detailed so as to make the main point of the figure/table clear even without the accompanying text
    * Graphs/tables/etc (4/4 pts)
        * Look great
    * Surveys, sampling, and observational data appendix (0/10 pts)
        * Not done - include some idealized methodology/survey like how we did for the elections paper 
        * Ie if you could make an ideal dataset for this model how would you go about doing it
    * Referencing (3/4 pts)
        * 1-2 broken references
    * Commits (2/2 pts)
        * Good
    * Sketches (2/2 pts)
        * Good but some of these are from the old paper lol so just go through them
    * Simulation (3/4 pts)
        * Add interaction between variables
    * Tests (2/4 pts)
        * Use testthat!!!!!!
    * Parquet (0/1 pts)
        * SAVE DATA AS PARQUET FILE
        * Use the arrow package
    * Reproducible workflow (4/4 pts)
        * Looks good to me but I would definitely double check and confirm it’s all reproducible
    * Enhancements (4/4 pts)
        * Datasheet! You still have templates in there tho so just clean up the repository
    * Miscellaneous (3/3 pts)
        * Overall a really good effort
6. Estimated overall mark: 81 out of 112
7. Any other comments: really good effort, mostly minor issues to fix. Clean up the repository you have old files from the starter folder

**Comment by brucejczhang** [comment]
Thank you for your review of my repo. I have made changes to my introduction, including an estimand statement. I have also made additions to the appendices by adding an idealized methodology and made changes to other sections based on your comments.
